/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20 } from "./ERC20";
export type { IERC20 } from "./IERC20";

export { ERC20__factory } from "./factories/ERC20__factory";
export { IERC20__factory } from "./factories/IERC20__factory";
